---
# TODO: Remove the inlined job definition once
- job:
    name: telemetry-container-image-content-provider-test
    parent: cifmw-base-minimal
    description: |
      Build sg-core and mysqld-exporter container images from the
      current change and serve them from a local registry for
      dependent jobs.
    required-projects:
      - name: openstack-k8s-operators/ci-framework
        override-checkout: main
      - name: openstack-k8s-operators/sg-core
      - name: openstack-k8s-operators/mysqld_exporter
    run:
      - ci/playbooks/container-image-content-provider.yml
    vars:
      container_images:
        - src: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/sg-core"
          name: sg-core
          update_var: cifmw_update_containers_ceilometersgcoreImage
        - src: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/mysqld_exporter"
          name: mysqld-exporter
          update_var: cifmw_update_containers_ceilometermysqldexporterImage

- project:
    name: openstack-k8s-operators/sg-core
    github-check:
      jobs:
        - telemetry-container-image-content-provider-test
        - telemetry-openstack-meta-content-provider-master:
            override-checkout: main
        - functional-tests-osp18:
            override-checkout: master
            dependencies:
              - telemetry-openstack-meta-content-provider-master
              - telemetry-container-image-content-provider-test
